twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # Définition du thème par défaut pour les formulaires
    form_themes: ['form/bootstrap_4_layout.html.twig']
    exception_controller:  App\Controller\ExceptionController::redirectException